- platform: mqtt
  name: hvac
  modes:
    - "off"
    - "cool"
    - "heat"
    - "fan_only"
  swing_modes:
    - "on"
    - "off"
  fan_modes:
    - "high"
    - "medium"
    - "low"
  
  availability_topic: "001/tele/cambria/hvac/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"


  current_temperature_topic: "001/tele/cambria/2/laundry/bme280/SENSOR"
  current_temperature_template: "{{ value_json['BME280'].Temperature }}"

  power_command_topic: "study/ac/power/set"
  mode_command_topic: "study/ac/mode/set"
  temperature_command_topic: "study/ac/temperature/set"
  fan_mode_command_topic: "study/ac/fan/set"
  swing_mode_command_topic: "study/ac/swing/set"
  precision: 1.0