#Binary Sensors for HVAC Unit

- platform: mqtt
  name: "HVAC Fan"
  state_topic: "001/cambria/hvac/fan"
  payload_on: "1"
  payload_off: "0"
  availability_topic: "001/tele/cambria/hvac/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1

- platform: mqtt
  name: "HVAC Heat"
  state_topic: "001/cambria/hvac/heat"
  payload_on: "1"
  payload_off: "0"
  availability_topic: "001/tele/cambria/hvac/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1

- platform: mqtt
  name: "HVAC Heat High"
  state_topic: "001/cambria/hvac/heat1"
  payload_on: "1"
  payload_off: "0"
  availability_topic: "001/tele/cambria/hvac/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1


- platform: mqtt
  name: "HVAC Cool"
  state_topic: "001/cambria/hvac/cool"
  payload_on: "1"
  payload_off: "0"
  availability_topic: "001/tele/cambria/hvac/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
