#######################
# DOORS & WINDOWS
######################

- platform: mqtt
  name: "Couch Window"
  state_topic: "001/stat/cambria/1/living_room/doors/WINDOW"
  payload_on: "0"
  payload_off: "1"
  availability_topic: "001/tele/cambria/1/living_room/doors/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: window   # also: window, garage_door or opening
  qos: 1