#A7F988
#A7F98C
#A7F984
#A7F989
#A7F982
#A7F985
#A7F981
#A7F983


- platform: mqtt
  name: "RFKey 1"
  state_topic: "001/tele/cambria/rf/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "A7F988"
  payload_off: "000000"
  availability_topic: "001/tele/cambria/rf/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1

- platform: mqtt
  name: "RFKey 2"
  state_topic: "001/tele/cambria/rf/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "A7F98C"
  payload_off: "000000"
  availability_topic: "001/tele/cambria/rf/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1

- platform: mqtt
  name: "RFKey 3"
  state_topic: "001/tele/cambria/rf/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "A7F984"
  payload_off: "000000"
  availability_topic: "001/tele/cambria/rf/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1

- platform: mqtt
  name: "RFKey 4"
  state_topic: "001/tele/cambria/rf/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "A7F989"
  payload_off: "000000"
  availability_topic: "001/tele/cambria/rf/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1

- platform: mqtt
  name: "RFKey 5"
  state_topic: "001/tele/cambria/rf/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "A7F982"
  payload_off: "000000"
  availability_topic: "001/tele/cambria/rf/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1

- platform: mqtt
  name: "RFKey 6"
  state_topic: "001/tele/cambria/rf/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "A7F985"
  payload_off: "000000"
  availability_topic: "001/tele/cambria/rf/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1

- platform: mqtt
  name: "RFKey 7"
  state_topic: "001/tele/cambria/rf/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "A7F981"
  payload_off: "000000"
  availability_topic: "001/tele/cambria/rf/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1

- platform: mqtt
  name: "RFKey 8"
  state_topic: "001/tele/cambria/rf/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "A7F983"
  payload_off: "000000"
  availability_topic: "001/tele/cambria/rf/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
