- platform: mqtt
  name: "Kitchen Sink Light"
  state_topic: "001/stat/cambria/1/kitchen/sink_light/RESULT"  
  value_template: "{{ value_json.POWER }}"
  command_topic: "001/cmnd/cambria/1/kitchen/sink_light/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "001/tele/cambria/1/kitchen/sink_light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "Alans Night Lamp"
  state_topic: "001/stat/cambria/2/alans_room/night_light/RESULT"  
  value_template: "{{ value_json.POWER }}"
  command_topic: "001/cmnd/cambria/2/alans_room/night_light/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "001/tele/cambria/2/alans_room/night_light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "Garage"
  state_topic: "001/stat/cambria/1/garage/light/RESULT"  
  value_template: "{{ value_json.POWER }}"
  command_topic: "001/cmnd/cambria/1/garage/light/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "001/tele/cambria/1/garage/light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false


- platform: mqtt
  name: "Chandleir"
  state_topic: "001/stat/cambria/2/loft/light/RESULT"  
  value_template: "{{ value_json.POWER1 }}"
  command_topic: "001/cmnd/cambria/2/loft/light/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "001/tele/cambria/2/loft/light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false


- platform: mqtt
  name: "Loft"
  state_topic: "001/stat/cambria/2/loft/light/RESULT"  
  value_template: "{{ value_json.POWER2 }}"
  command_topic: "001/cmnd/cambria/2/loft/light/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "001/tele/cambria/2/loft/light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false


- platform: mqtt
  name: "Porch"
  state_topic: "001/stat/cambria/1/main_door/light/RESULT"  
  value_template: "{{ value_json.POWER1 }}"
  command_topic: "001/cmnd/cambria/1/main_door/light/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "001/tele/cambria/1/main_door/light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false


- platform: mqtt
  name: "Main Entrance"
  state_topic: "001/stat/cambria/1/main_door/light/RESULT"  
  value_template: "{{ value_json.POWER2 }}"
  command_topic: "001/cmnd/cambria/1/main_door/light/POWER2"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "001/tele/cambria/1/main_door/light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "Backyard"
  state_topic: "001/stat/cambria/1/backyard/light/RESULT"  
  value_template: "{{ value_json.POWER }}"
  command_topic: "001/cmnd/cambria/1/backyard/light/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "001/tele/cambria/1/backyard/light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false