#pragma once
#define USE_API
#define USE_HOMEASSISTANT_TIME
#define USE_JSON
#define USE_LOGGER
#define USE_MQTT
#define USE_SENSOR
#define USE_STATUS_LED
#define USE_SWITCH
#define USE_TEXT_SENSOR
#define USE_TIME
#define USE_WIFI
