#Timer for Garage
garage_timer_slider:
  name: Garage Timer
  min: 1
  max: 60
  step: 1

#Maximum Humidity at which triggers ON
max_humidity_slider:
  name: Maximum Humidity
  min: 15
  max: 50
  step: 1

#Minimam Humidity at which triggers ON
min_humidity_slider:
  name: Minimum Humidity
  min: 15
  max: 50
  step: 1

laundry_max_temperature:
  name: Laundry Maximum Temperature
  min: 50
  max: 120
  step: 10
