#Turn OFF Garage Lights
- alias: 'LIGHT: Auto turn off Garage lights'
  trigger:
  - entity_id: light.garage_light
    platform: state
    to: 'on'
    for: '00:{{ states("input_number.garage_timer_slider") | int }} :00'
  action:
    service: homeassistant.turn_off
    entity_id: light.garage_light

##########################################################

#Turn ON Garage Lights
- alias: 'LIGHT: Turn on Garage Lights  Kitchen Door Open'
  trigger:
  - entity_id: binary_sensor.kitchen_door_sensor_aqara
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.garage_door
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.garage_occupancy_aqara
    platform: state
    from: 'off'
    to: 'on'
  - entity_id: binary_sensor.garage_motion_aqara
    platform: state
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.garage_light

##########################################################
- alias: 'SYSTEM: Reset Garage Timer'
  trigger:
  - at: 06:00:00
    platform: time
  condition: []
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.garage_timer_slider
      value: 5