# Trigger Alartm when in Armed Mode
- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: binary_sensor.backyard_door
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.couch_window
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.rf_backyard_glass_door
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.rf_front_door
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.rf_kitchen_door
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.ha_alarm


#Notify when Alarm goes on
- alias: 'Send notification when alarm triggered'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'triggered'
  action:
    - service: notify.notify
      data:
        message: "ALARM! The alarm has been triggered"
  action:
    service: notify.mypushbullet
    data_template:
      title: "ALARM! House"
      message: "Home Alarm is triggered"


- alias: 'Disarm alarm when Phone is in Range'
  trigger:
    platform: state
    entity_id: device_tracker.kc_phone
    # trigger for determining when at home
    from: 'not_home'
    to: 'home'
  trigger:
    platform: state
    entity_id: device_tracker.ec_phone
    # trigger for determining when at home
    from: 'not_home'
    to: 'home'
  trigger:
    platform: state
    entity_id: device_tracker.fm_phone
    # trigger for determining when at home
    from: 'not_home'
    to: 'home'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.house_alarm
