#Turn OFF LOFT Lights
- alias: 'LIGHT: Turn off Loft when not Occupied'
  trigger:
  - entity_id: binary_sensor.living_room_occupancy_aqara
    from: 'Occupied'
    platform: state
    to: 'Clear'
  action:
    service: homeassistant.turn_off
    entity_id: light.loft

###########################################################
- alias: 'LIGHT: Turn off Kitchen Sink Light'
  trigger:
  - entity_id: binary_sensor.kitchen_occupancy_aqara
    from: 'Occupied'
    platform: state
    to: 'Clear'
  action:
    service: homeassistant.turn_off
    entity_id: light.kitchen_sink_light

###########################################################
- alias: 'LIGHT: Turn off Garage Light'
  trigger:
  - entity_id: binary_sensor.living_room_occupancy_aqara
    from: 'Occupied'
    platform: state
    to: 'Clear'
  action:
    service: homeassistant.turn_off
    entity_id: light.garage_light
