#Turn OFF Garage Lights
- id: '874115816452007'
  alias: 'LIGHT: AUTO Turn on Garage on Kitchen Door Open'
  description: Turn on Kitchen Light
  trigger:
  - entity_id: binary_sensor.rf_kitchen_door
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - alias: ''
    data:
      entity_id: light.garage
    service: light.turn_on

#Turn OFF Garage Lights
- id: '164874115852007'
  alias: 'LIGHT: AUTO Turn on Garage on Garage Door Open'
  description: Turn on Kitchen Light
  trigger:
  - entity_id: binary_sensor.rf_kitchen_door
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - alias: ''
    data:
      entity_id: light.garage
    service: light.turn_on
