#Turn OFF Garage Lights
- alias: 'LIGHT: RF Remote'
  trigger:
  - entity_id: binary_sensor.rfkey_1
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
    service: light.turn_on
    entity_id: light.kitchen_sink_light

