- alias: "Z: TestPushBullet"
  trigger:
    platform: numeric_state
    entity_id: input_number.garage_timer_slider
    above: 15
  action:
    service: notify.mypushbullet
    data_template:
      title: "Garage light timer"
      message: "Timer changed. Reset it back in an hour"