#Turn ON Kitchen Lights with Chandleri lights at night
- alias: 'LIGHT: Kitchen Light on at night when Chandeleir is Turned On'
  trigger:
  - entity_id: light.chandelier
    from: 'off'
    platform: state
    to: 'on'
  condition:
    - condition: time
      after: '22:00:00'
      before: '06:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.kitchen_sink_light

#################################################
- alias: 'LIGHT: Kitchen Light OFF at night when Chandeleir is Turned OFF'
  trigger:
  - entity_id: light.chandelier
    from: 'on'
    platform: state
    to: 'off'
  condition:
    - condition: time
      after: '22:00:00'
      before: '06:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.kitchen_sink_light

################################################
- alias: 'LIGHT: Outdoor Lights ON'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  condition: []
  action:
    service: homeassistant.turn_on
    entity_id: group.outdoor_lights


#################################################
- alias: 'LIGHT: Outdoor Lights OFF'
  trigger:
    platform: sun
    event: sunrise
    offset: '00:30:00'
  condition: []
  action:
    service: homeassistant.turn_off
    entity_id: group.outdoor_lights

#################################################
- alias: 'LIGHT: Auto on at night'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  condition: []
  action:
    service: homeassistant.turn_on
    entity_id: group.indoor_default_on_lights


