#################### COMMON SETTINGS #########################
esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  arduino_version: espressif8266@2.2.3
wifi:
  networks:
  - ssid: HOME2G
    password: !secret WIFI_password
    priority: 3
  - ssid: IOT
    password: !secret WIFI_password
    priority: 2
  - ssid: phone
    password: !secret WIFI_password
    priority: 1
  ap:
    ssid: $devicename
    password: !secret AP_password
    ap_timeout: 5min

logger: 

api:

ota:
  safe_mode: True
  id: myota
  
#web_server:
#  port: 80

# Example configuration entry
text_sensor:
  - platform: wifi_info
    ip_address:
      name: $devicename IP
    ssid:
      name: $devicename SSID
    bssid:
      name: $devicename BSSID
  - platform: version
    name: "$devicename Version"

#################### COMMON SETTINGS #########################
