substitutions:
  devicename: alans_night_lamp
  $upper_devicename: Alans
  
<<: !include .base.common1m.yaml

#Sonoff pin mapping
#GPIO0	Button (inverted)
#GPIO1	TX pin (C1 Pin 2)
#GPIO3	RX pin (C1 Pin 3)
#GPIO12	Relay
#GPIO13	Green LED (inverted)
#GPIO14	Optional Sensor (C1 Pin 5)


status_led:
  pin:
    number: GPIO13
    inverted: yes

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - light.toggle: $devicename

output:
  - platform: gpio
    id: light_relay
    pin: GPIO12

light:
  - platform: binary
    id: $devicename
    name: $upper_devicename Night Lamp
    output: light_relay
