substitutions:
  devicename: humidity_controller
  device_shortname: Controller

<<: !include .base.common1m.yaml

#Sonoff pin mapping
#GPIO0	Button (inverted)
#GPIO1	TX pin (C1 Pin 2)
#GPIO3	RX pin (C1 Pin 3)
#GPIO12	Relay
#GPIO13	Green LED (inverted)
#GPIO14	Optional Sensor (C1 Pin 5)

binary_sensor:
  - platform: status
    name:  "$devicename Status"
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay
sensor:
  - platform: wifi_signal
    name: "$devicename WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "$devicename uptime"

switch:
  - platform: restart
    name: "$devicename Restart"
  - platform: gpio
    name: "Humidifier Relay"
    pin: GPIO12
    id: relay
  - platform: restart
    name: ${devicename} Restart

status_led:
  pin:
    number: GPIO13
    inverted: yes
    