substitutions:
  devicename: laundry_bmp280
  device_shortname: Laundry

<<: !include .base.common_8266.yaml

i2c:
  sda: D1
  scl: D2
  scan: True

#BMP280 Sensor
sensor:
  - platform: bmp280
    temperature:
      name: ${device_shortname} Temperature
      oversampling: 16x
    address: 0x76
    update_interval: 60s
  - platform: wifi_signal
    name: "$devicename WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "$devicename uptime"
    
switch:
  - platform: restart
    name: "$devicename Restart"



binary_sensor:
  - platform: status
    name:  "$devicename Status"


status_led:
  pin:
    number: GPIO2
    inverted: yes    