esphome:
  name: loft_bme280
  platform: ESP8266
  board: d1_mini


wifi:
  ssid: "IOT"
  password: "608980608980"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "loft_bme280"
    password: "1234567890"

i2c:
  sda: D1
  scl: D2
  scan: True


# Example configuration entry
sensor:
  - platform: bme280
    temperature:
      name: "Loft Temperature"
      oversampling: 16x
    pressure:
      name: "Loft Pressure"
    humidity:
      name: "Loft Humidity"
    address: 0x76
    update_interval: 60s

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
