
substitutions:
  devicename: power_meter
  device_shortname: Garage

<<: !include .base.common_8266.yaml

spi:
  clk_pin: 18
  miso_pin: 19
  mosi_pin: 23

sensor:
  - platform: atm90e32
    cs_pin: 5
    phase_a:
      voltage:
        name: "EMON Line Voltage A"
      current:
        name: "EMON CT1 Current"
      power:
        name: "EMON Active Power CT1"
      gain_voltage: 41820
      gain_ct: 25498
    phase_c:
      current:
        name: "EMON CT2 Current"
      power:
        name: "EMON Active Power CT2"
      gain_voltage: 3920
      gain_ct: 39473
    frequency:
      name: "EMON Line Frequency"
    line_frequency: 60Hz
    gain_pga: 2X
    update_interval: 1s